In [34]:
import pandas as pd
import numpy as np
from kmodes.kprototypes import KPrototypes

In [35]:
df = pd.read_csv('dataset.txt',sep=";")
df

,plant,pollutant,cost range,Moisture,Temperature
0,SweetFlag,Methanol,200,High,Low
1,RedAmarnath,Napthalene,200,Normal,Normal
2,RedAmarnath,Phenanthrene,200,Normal,Normal
3,Evergreen azalea,Toluene,400,Low,Low
4,bougainvillea,Xylene,200,High,Normal
5,beach morning glory,Methanol,500,Normal,High
6,vetiver,Benzene,60,Normal,Normal
7,vetiver,Toluene,60,Normal,Normal
8,vetiver,Ethylbenzene,60,Normal,Normal
9,vetiver,Xylene,60,Normal,Normal
10,Asian pigeonwings,Formaldehyde,200,High,Normal
11,water hyacinth,Methanol,100,High,Low
12,cucumber,Alkanes,150,High,Normal
13,treasure flower,alkanes,500,Low,High
14,Jasmine,Napthalene,410,Low,Normal
15,Jasmine,Phenanthrene,410,Low,Normal
16,Hibiscus,Napthalene,200,High,Low
17,Hibiscus,Napthalene,200,High,Low
18,jungle geranium,Napthalene,160,High,Normal
19,jungle geranium,Phenanthrene,160,High,Normal
20,jungle geranium,Polycyclic Aromatic Hydrocarbons,160,High,Normal
21,English Ivy,Particulate matter,750,Low,Low
22,RyeGrass,Petroleum Hydrocarbons,50,High,Normal
23,RyeGrass,Phenanthrene,50,High,Normal
24,hoary stock,Alkanes,150,Normal,Low
25,rice,Methanol,150,High,Normal
26,common bean,crude oil,200,High,Normal
27,common bean,Phenanthrene,200,High,Normal
28,common bean,Octadexane,200,High,Normal
29,pea,Polyaromatic hydrocarbon,120,High,Normal
30,yellow elder,Alkanes,350,Normal,High
31,glaucous willow,Polycyclic Aromatic Hydrocarbons,600,High,Normal
32,purpleosier willow,Polycyclic Aromatic Hydrocarbons,300,High,Normal
33,Dandy,Alkanes,100,Low,High
34,Trumpet Flower,Volatile Hydrocarbons,250,Low,Normal
35,Trumpet Flower,Alkanes,250,Low,Normal
36,broadbean,Alkanes,200,Normal,Normal
37,broadbean,Phenanthrene,200,Normal,Normal
38,broadbean,Crude oil,200,Normal,Normal
39,broadbean,Hexadecane,200,Normal,Normal

In [36]:
df['pollutant'].unique()

array(['Methanol', 'Napthalene', 'Phenanthrene', 'Toluene', 'Xylene',
       'Benzene', 'Ethylbenzene', 'Formaldehyde', 'Alkanes', 'alkanes',
       'Polycyclic Aromatic Hydrocarbons', 'Particulate matter',
       'Petroleum Hydrocarbons', 'crude oil', 'Octadexane',
       'Polyaromatic hydrocarbon', 'Volatile Hydrocarbons', 'Crude oil',
       'Hexadecane'], dtype=object)

In [37]:
df['Temperature'].unique(),df['Moisture'].unique()

(array(['Low', 'Normal', 'High'], dtype=object),
 array(['High', 'Normal', 'Low'], dtype=object))

In [38]:
pollutants = list(df['pollutant'])
pollutants
# for i in pollutants:

['Methanol',
 'Napthalene',
 'Phenanthrene',
 'Toluene',
 'Xylene',
 'Methanol',
 'Benzene',
 'Toluene',
 'Ethylbenzene',
 'Xylene',
 'Formaldehyde',
 'Methanol',
 'Alkanes',
 'alkanes',
 'Napthalene',
 'Phenanthrene',
 'Napthalene',
 'Napthalene',
 'Napthalene',
 'Phenanthrene',
 'Polycyclic Aromatic Hydrocarbons',
 'Particulate matter',
 'Petroleum Hydrocarbons',
 'Phenanthrene',
 'Alkanes',
 'Methanol',
 'crude oil',
 'Phenanthrene',
 'Octadexane',
 'Polyaromatic hydrocarbon',
 'Alkanes',
 'Polycyclic Aromatic Hydrocarbons',
 'Polycyclic Aromatic Hydrocarbons',
 'Alkanes',
 'Volatile Hydrocarbons',
 'Alkanes',
 'Alkanes',
 'Phenanthrene',
 'Crude oil',
 'Hexadecane']

In [39]:
df_array = df.values

df_array[:, 2] = df_array[:, 2].astype(float)

df_array

array([['SweetFlag', 'Methanol', 200.0, 'High', 'Low'],
       ['RedAmarnath', 'Napthalene', 200.0, 'Normal', 'Normal'],
       ['RedAmarnath', 'Phenanthrene', 200.0, 'Normal', 'Normal'],
       ['Evergreen azalea', 'Toluene', 400.0, 'Low', 'Low'],
       ['bougainvillea', 'Xylene', 200.0, 'High', 'Normal'],
       ['beach morning glory', 'Methanol', 500.0, 'Normal', 'High'],
       ['vetiver', 'Benzene', 60.0, 'Normal', 'Normal'],
       ['vetiver', 'Toluene', 60.0, 'Normal', 'Normal'],
       ['vetiver', 'Ethylbenzene', 60.0, 'Normal', 'Normal'],
       ['vetiver', 'Xylene', 60.0, 'Normal', 'Normal'],
       ['Asian pigeonwings', 'Formaldehyde', 200.0, 'High', 'Normal'],
       ['water hyacinth', 'Methanol', 100.0, 'High', 'Low'],
       ['cucumber', 'Alkanes', 150.0, 'High', 'Normal'],
       ['treasure flower', 'alkanes', 500.0, 'Low', 'High'],
       ['Jasmine', 'Napthalene', 410.0, 'Low', 'Normal'],
       ['Jasmine', 'Phenanthrene', 410.0, 'Low', 'Normal'],
       ['Hibiscus', 'Napthalene', 200.0, 'High', 'Low'],
       ['Hibiscus', 'Napthalene', 200.0, 'High', 'Low'],
       ['jungle geranium', 'Napthalene', 160.0, 'High', 'Normal'],
       ['jungle geranium', 'Phenanthrene', 160.0, 'High', 'Normal'],
       ['jungle geranium', 'Polycyclic Aromatic Hydrocarbons', 160.0,
        'High', 'Normal'],
       ['English Ivy', 'Particulate matter', 750.0, 'Low', 'Low'],
       ['RyeGrass', 'Petroleum Hydrocarbons', 50.0, 'High', 'Normal'],
       ['RyeGrass', 'Phenanthrene', 50.0, 'High', 'Normal'],
       ['hoary stock', 'Alkanes', 150.0, 'Normal', 'Low'],
       ['rice', 'Methanol', 150.0, 'High', 'Normal'],
       ['common bean', 'crude oil', 200.0, 'High', 'Normal'],
       ['common bean', 'Phenanthrene', 200.0, 'High', 'Normal'],
       ['common bean', 'Octadexane', 200.0, 'High', 'Normal'],
       ['pea', 'Polyaromatic hydrocarbon', 120.0, 'High', 'Normal'],
       ['yellow elder', 'Alkanes', 350.0, 'Normal', 'High'],
       ['glaucous willow', 'Polycyclic Aromatic Hydrocarbons', 600.0,
        'High', 'Normal'],
       ['purpleosier willow', 'Polycyclic Aromatic Hydrocarbons', 300.0,
        'High', 'Normal'],
       ['Dandy', 'Alkanes', 100.0, 'Low', 'High'],
       ['Trumpet Flower', 'Volatile Hydrocarbons', 250.0, 'Low',
        'Normal'],
       ['Trumpet Flower', 'Alkanes', 250.0, 'Low', 'Normal'],
       ['broadbean', 'Alkanes', 200.0, 'Normal', 'Normal'],
       ['broadbean', 'Phenanthrene', 200.0, 'Normal', 'Normal'],
       ['broadbean', 'Crude oil', 200.0, 'Normal', 'Normal'],
       ['broadbean', 'Hexadecane', 200.0, 'Normal', 'Normal']],
      dtype=object)

In [40]:
kproto = KPrototypes(n_clusters=3, verbose=2,max_iter=20)
clusters = kproto.fit_predict(df_array, categorical=[0,1,3,4])

Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 1, iteration: 1/20, moves: 6, ncost: 160570.51693451017
Run: 1, iteration: 2/20, moves: 1, ncost: 159936.73791905912
Run: 1, iteration: 3/20, moves: 0, ncost: 159936.73791905912
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 2, iteration: 1/20, moves: 16, ncost: 164006.74242170525
Run: 2, iteration: 2/20, moves: 1, ncost: 159936.73791905912
Run: 2, iteration: 3/20, moves: 0, ncost: 159936.73791905912
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 3, iteration: 1/20, moves: 3, ncost: 170139.97299852408
Run: 3, iteration: 2/20, moves: 0, ncost: 170139.97299852408
Init: initializing centroids
Init: initializing clusters
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 4, iteration: 1/20, moves: 17, ncost: 164006.74242170525
Run: 4, iteration: 2/20, moves: 1, ncost: 159936.73791905915
Run: 4, iteration: 3/20, moves: 0, ncost: 159936.73791905915
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 5, iteration: 1/20, moves: 2, ncost: 159936.73791905915
Run: 5, iteration: 2/20, moves: 0, ncost: 159936.73791905915
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 6, iteration: 1/20, moves: 14, ncost: 341955.3706702444
Run: 6, iteration: 2/20, moves: 12, ncost: 159936.73791905912
Run: 6, iteration: 3/20, moves: 0, ncost: 159936.73791905912
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 7, iteration: 1/20, moves: 4, ncost: 159936.73791905915
Run: 7, iteration: 2/20, moves: 0, ncost: 159936.73791905915
Init: initializing centroids
Init: initializing clusters
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 8, iteration: 1/20, moves: 0, ncost: 159936.73791905915
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 9, iteration: 1/20, moves: 16, ncost: 164006.74242170525
Run: 9, iteration: 2/20, moves: 1, ncost: 159936.73791905912
Run: 9, iteration: 3/20, moves: 0, ncost: 159936.73791905912
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 10, iteration: 1/20, moves: 3, ncost: 170139.97299852408
Run: 10, iteration: 2/20, moves: 0, ncost: 170139.97299852408
Best run was number 1

In [41]:
print(kproto.cluster_centroids_)

[array([[ 73.33333333],
       [196.95652174],
       [490.        ]]), array([['vetiver', 'Alkanes', 'High', 'Normal'],
       ['broadbean', 'Napthalene', 'High', 'Normal'],
       ['Jasmine', 'Alkanes', 'Low', 'High']], dtype='<U10')]

In [42]:
cluster_dict=[]
for c in clusters:
    cluster_dict.append(c)

In [43]:
cluster_dict

[1,
 1,
 1,
 2,
 1,
 2,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 2,
 2,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1]

In [44]:
df['cluster'] = cluster_dict
df

,plant,pollutant,cost range,Moisture,Temperature,cluster
0,SweetFlag,Methanol,200,High,Low,1
1,RedAmarnath,Napthalene,200,Normal,Normal,1
2,RedAmarnath,Phenanthrene,200,Normal,Normal,1
3,Evergreen azalea,Toluene,400,Low,Low,2
4,bougainvillea,Xylene,200,High,Normal,1
5,beach morning glory,Methanol,500,Normal,High,2
6,vetiver,Benzene,60,Normal,Normal,0
7,vetiver,Toluene,60,Normal,Normal,0
8,vetiver,Ethylbenzene,60,Normal,Normal,0
9,vetiver,Xylene,60,Normal,Normal,0
10,Asian pigeonwings,Formaldehyde,200,High,Normal,1
11,water hyacinth,Methanol,100,High,Low,0
12,cucumber,Alkanes,150,High,Normal,1
13,treasure flower,alkanes,500,Low,High,2
14,Jasmine,Napthalene,410,Low,Normal,2
15,Jasmine,Phenanthrene,410,Low,Normal,2
16,Hibiscus,Napthalene,200,High,Low,1
17,Hibiscus,Napthalene,200,High,Low,1
18,jungle geranium,Napthalene,160,High,Normal,1
19,jungle geranium,Phenanthrene,160,High,Normal,1
20,jungle geranium,Polycyclic Aromatic Hydrocarbons,160,High,Normal,1
21,English Ivy,Particulate matter,750,Low,Low,2
22,RyeGrass,Petroleum Hydrocarbons,50,High,Normal,0
23,RyeGrass,Phenanthrene,50,High,Normal,0
24,hoary stock,Alkanes,150,Normal,Low,1
25,rice,Methanol,150,High,Normal,1
26,common bean,crude oil,200,High,Normal,1
27,common bean,Phenanthrene,200,High,Normal,1
28,common bean,Octadexane,200,High,Normal,1
29,pea,Polyaromatic hydrocarbon,120,High,Normal,0
30,yellow elder,Alkanes,350,Normal,High,2
31,glaucous willow,Polycyclic Aromatic Hydrocarbons,600,High,Normal,2
32,purpleosier willow,Polycyclic Aromatic Hydrocarbons,300,High,Normal,1
33,Dandy,Alkanes,100,Low,High,0
34,Trumpet Flower,Volatile Hydrocarbons,250,Low,Normal,1
35,Trumpet Flower,Alkanes,250,Low,Normal,1
36,broadbean,Alkanes,200,Normal,Normal,1
37,broadbean,Phenanthrene,200,Normal,Normal,1
38,broadbean,Crude oil,200,Normal,Normal,1
39,broadbean,Hexadecane,200,Normal,Normal,1

In [47]:
df[df['cluster']== 0].head(10)

,plant,pollutant,cost range,Moisture,Temperature,cluster
6,vetiver,Benzene,60,Normal,Normal,0
7,vetiver,Toluene,60,Normal,Normal,0
8,vetiver,Ethylbenzene,60,Normal,Normal,0
9,vetiver,Xylene,60,Normal,Normal,0
11,water hyacinth,Methanol,100,High,Low,0
22,RyeGrass,Petroleum Hydrocarbons,50,High,Normal,0
23,RyeGrass,Phenanthrene,50,High,Normal,0
29,pea,Polyaromatic hydrocarbon,120,High,Normal,0
33,Dandy,Alkanes,100,Low,High,0

In [48]:
df[df['cluster']== 1].head(10)

                plant     pollutant  cost range Moisture Temperature  cluster
0           SweetFlag      Methanol         200     High         Low        1
1         RedAmarnath    Napthalene         200   Normal      Normal        1
2         RedAmarnath  Phenanthrene         200   Normal      Normal        1
4       bougainvillea        Xylene         200     High      Normal        1
10  Asian pigeonwings  Formaldehyde         200     High      Normal        1
12           cucumber       Alkanes         150     High      Normal        1
16           Hibiscus    Napthalene         200     High         Low        1
17           Hibiscus    Napthalene         200     High         Low        1
18    jungle geranium    Napthalene         160     High      Normal        1
19    jungle geranium  Phenanthrene         160     High      Normal        1

In [49]:
df[df['cluster']== 2].head(10)

,plant,pollutant,cost range,Moisture,Temperature,cluster
3,Evergreen azalea,Toluene,400,Low,Low,2
5,beach morning glory,Methanol,500,Normal,High,2
13,treasure flower,alkanes,500,Low,High,2
14,Jasmine,Napthalene,410,Low,Normal,2
15,Jasmine,Phenanthrene,410,Low,Normal,2
21,English Ivy,Particulate matter,750,Low,Low,2
30,yellow elder,Alkanes,350,Normal,High,2
31,glaucous willow,Polycyclic Aromatic Hydrocarbons,600,High,Normal,2